// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_KeyMapped_screen_init();
    ui_KeyMappedSecondary_screen_init();
    ui_StatusBar_init();
    ui_MusicScreen_screen_init();
    ui_MusicScreenSecondary_screen_init();
    ui_PcStatusScreen_screen_init();
    ui_PcStatusScreenSecondary_screen_init();
    ui_HaScreen_screen_init();
    ui_HaScreenSecondary_screen_init();
    ui_SettingScreen_screen_init();
    ui_SettingScreenSecondary_screen_init();
    
    ui____initial_actions0 = lv_obj_create(NULL);
    ui_set_active_screen_tag(UI_SCREEN_MAIN);
    lv_disp_load_scr(ui_MainScreen);
}

void ui_destroy(void)
{
    ui_MainScreen_screen_destroy();
    ui_KeyMapped_screen_destroy();
    ui_KeyMappedSecondary_screen_destroy();
    ui_MusicScreen_screen_destroy();
    ui_MusicScreenSecondary_screen_destroy();
    ui_PcStatusScreen_screen_destroy();
    ui_PcStatusScreenSecondary_screen_destroy();
    ui_HaScreen_screen_destroy();
    ui_HaScreenSecondary_screen_destroy();
    ui_SettingScreen_screen_destroy();
    ui_SettingScreenSecondary_screen_destroy();
}
