// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

///////////////////// SCREENS ////////////////////

#include "ui_MainScreen.h"

///////////////////// VARIABLES ////////////////////


// FONTS
LV_FONT_DECLARE(ui_font_BebasNeueFont48);
LV_FONT_DECLARE(ui_font_BebasNeueFont24);
LV_FONT_DECLARE(ui_font_BebasNeueFont86);
LV_FONT_DECLARE(ui_font_BebasNeueFont36);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
