// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_MainScreen.h"
#include "ui_KeyMapped.h"
#include "ui_KeyMappedSecondary.h"
#include "ui_MusicScreen.h"
#include "ui_MusicScreenSecondary.h"
#include "ui_PcStatusScreen.h"
#include "ui_PcStatusScreenSecondary.h"
#include "ui_HaScreen.h"
#include "ui_HaScreenSecondary.h"
#include "ui_SettingScreen.h"
#include "ui_SettingScreenSecondary.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_BebasNeueFont48);
LV_FONT_DECLARE(ui_font_BebasNeueFont24);
LV_FONT_DECLARE(ui_font_BebasNeueFont16);
LV_FONT_DECLARE(ui_font_BebasNeueFont28);
LV_FONT_DECLARE(ui_font_BebasNeueFont86);
LV_FONT_DECLARE(ui_font_BebasNeueFont36);
LV_FONT_DECLARE(ui_font_BebasNeueFont14);
LV_FONT_DECLARE(ui_font_FontCKJGT16);
LV_FONT_DECLARE(ui_font_FontCKJGT24);
LV_FONT_DECLARE(ui_font_FontCKJGT28);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
