// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Button5

lv_obj_t * ui_Button5_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button5;
    cui_Button5 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Button5, 100);
    lv_obj_set_height(cui_Button5, 50);
    lv_obj_set_x(cui_Button5, -398);
    lv_obj_set_y(cui_Button5, 13);
    lv_obj_set_align(cui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button5, lv_color_hex(0xF000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON5_NUM);
    children[UI_COMP_BUTTON5_BUTTON5] = cui_Button5;
    lv_obj_add_event_cb(cui_Button5, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button5, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Button5_create_hook(cui_Button5);
    return cui_Button5;
}

