// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

lv_obj_t * ui_HaScreenSecondary = NULL;
lv_obj_t * ui_Label4 = NULL;
static lv_obj_t * s_HaSecondaryTitle = NULL;
static lv_obj_t * s_LabelWifiValue = NULL;
static lv_obj_t * s_LabelModeValue = NULL;
static lv_obj_t * s_LabelVoiceValue = NULL;
static lv_obj_t * s_LabelTcpValue = NULL;
static lv_obj_t * s_LabelModuleAValue = NULL;
static lv_obj_t * s_LabelModuleBValue = NULL;
static lv_obj_t * s_LabelIpValue = NULL;
static lv_obj_t * s_LabelServerValue = NULL;
static lv_obj_t * s_ButtonExit = NULL;

static bool s_wifi_enabled = false;
static bool s_wifi_connected = false;
static int s_wifi_rssi = -100;
static bool s_tcp_connected = false;
static int s_work_mode = 0;
static bool s_voice_enabled = false;
static bool s_voice_recording = false;
static bool s_module_a_connected = false;
static bool s_module_b_connected = false;
static char s_ip_address[24] = "--";
static char s_server_endpoint[32] = "OFFLINE";

enum {
    UI_HA_WORK_MODE_WIRED = 0,
    UI_HA_WORK_MODE_BLUETOOTH = 1,
    UI_HA_WORK_MODE_2_4G = 2,
};

static void ha_secondary_forward_key(uint32_t key)
{
    lv_obj_t *active_screen = lv_scr_act();
    lv_group_t *g = lv_group_get_default();
    lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;
    if (target) {
        lv_event_send(target, LV_EVENT_KEY, (void *)key);
    }
}

static const char *ha_work_mode_text(int work_mode)
{
    switch (work_mode) {
        case UI_HA_WORK_MODE_WIRED: return "WIRED";
        case UI_HA_WORK_MODE_BLUETOOTH: return "BLUETOOTH";
        case UI_HA_WORK_MODE_2_4G: return "2.4G";
        default: return "UNKNOWN";
    }
}

static void ha_set_status_value(lv_obj_t *label, const char *text, lv_color_t color)
{
    if (!label) {
        return;
    }

    lv_label_set_text(label, text);
    lv_obj_set_style_text_color(label, color, LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void ha_refresh_wifi_status(void)
{
    char wifiText[40] = {0};
    if (!s_wifi_enabled) {
        snprintf(wifiText, sizeof(wifiText), "DISABLED");
        ha_set_status_value(s_LabelWifiValue, wifiText, lv_color_hex(0x94A3B8));
    } else if (s_wifi_connected) {
        snprintf(wifiText, sizeof(wifiText), "%d dBm", s_wifi_rssi);
        ha_set_status_value(s_LabelWifiValue, wifiText, lv_color_hex(0x22C55E));
    } else {
        snprintf(wifiText, sizeof(wifiText), "CONNECTING");
        ha_set_status_value(s_LabelWifiValue, wifiText, lv_color_hex(0xF59E0B));
    }

    if (s_LabelIpValue) {
        lv_label_set_text_fmt(s_LabelIpValue, "IP  %s", s_ip_address);
    }
}

static void ha_refresh_tcp_status(void)
{
    ha_set_status_value(s_LabelTcpValue,
                        s_tcp_connected ? "LINKED" : "WAITING",
                        s_tcp_connected ? lv_color_hex(0x22C55E) : lv_color_hex(0xF59E0B));
    if (s_LabelServerValue) {
        lv_label_set_text_fmt(s_LabelServerValue, "SERVER  %s", s_server_endpoint);
    }
}

static void ha_refresh_mode_status(void)
{
    ha_set_status_value(s_LabelModeValue, ha_work_mode_text(s_work_mode), lv_color_hex(0xFFFFFF));
}

static void ha_refresh_voice_status(void)
{
    if (!s_voice_enabled) {
        ha_set_status_value(s_LabelVoiceValue, "DISABLED", lv_color_hex(0x94A3B8));
    } else if (s_voice_recording) {
        ha_set_status_value(s_LabelVoiceValue, "RECORDING", lv_color_hex(0xEF4444));
    } else {
        ha_set_status_value(s_LabelVoiceValue, "READY", lv_color_hex(0x22C55E));
    }
}

static void ha_refresh_module_status(void)
{
    ha_set_status_value(s_LabelModuleAValue,
                        s_module_a_connected ? "ONLINE" : "OFFLINE",
                        s_module_a_connected ? lv_color_hex(0x22C55E) : lv_color_hex(0x94A3B8));
    ha_set_status_value(s_LabelModuleBValue,
                        s_module_b_connected ? "ONLINE" : "OFFLINE",
                        s_module_b_connected ? lv_color_hex(0x22C55E) : lv_color_hex(0x94A3B8));
}

static void ha_apply_cached_snapshot(void)
{
    ha_refresh_wifi_status();
    ha_refresh_tcp_status();
    ha_refresh_mode_status();
    ha_refresh_voice_status();
    ha_refresh_module_status();
}

void ui_HaScreenSecondary_set_wifi_status(bool enabled, bool connected, int rssi, const char *ip_address)
{
    s_wifi_enabled = enabled;
    s_wifi_connected = connected;
    s_wifi_rssi = rssi;
    snprintf(s_ip_address, sizeof(s_ip_address), "%s", ip_address ? ip_address : "--");
    ha_refresh_wifi_status();
}

void ui_HaScreenSecondary_set_tcp_status(bool connected, const char *server_endpoint)
{
    s_tcp_connected = connected;
    snprintf(s_server_endpoint, sizeof(s_server_endpoint), "%s", server_endpoint ? server_endpoint : "OFFLINE");
    ha_refresh_tcp_status();
}

void ui_HaScreenSecondary_set_mode_status(int work_mode)
{
    s_work_mode = work_mode;
    ha_refresh_mode_status();
}

void ui_HaScreenSecondary_set_voice_status(bool enabled, bool recording)
{
    s_voice_enabled = enabled;
    s_voice_recording = recording;
    ha_refresh_voice_status();
}

void ui_HaScreenSecondary_set_module_status(bool module_a_connected, bool module_b_connected)
{
    s_module_a_connected = module_a_connected;
    s_module_b_connected = module_b_connected;
    ha_refresh_module_status();
}

void ui_event_HaScreenSecondary(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_KEY) {
        return;
    }

    if ((uintptr_t)lv_event_get_param(e) == (uintptr_t)LV_KEY_ESC) {
        ui_set_active_screen_tag(UI_SCREEN_HA);
        _ui_screen_change(&ui_HaScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HaScreen_screen_init);
        lv_refr_now(NULL);
    }
}

void ui_event_ButtonExitHaSecondary(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        ha_secondary_forward_key(LV_KEY_ESC);
    }
}

void ui_HaScreenSecondary_screen_init(void)
{
    ui_HaScreenSecondary = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HaScreenSecondary, LV_OBJ_FLAG_SCROLLABLE);

    s_HaSecondaryTitle = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_align(s_HaSecondaryTitle, LV_ALIGN_TOP_MID);
    lv_obj_set_pos(s_HaSecondaryTitle, 0, 4);
    lv_label_set_text(s_HaSecondaryTitle, "HOME ASSISTANT");
    lv_obj_set_style_text_color(s_HaSecondaryTitle, lv_color_hex(0x6ADAE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_HaSecondaryTitle, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelWifi = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(labelWifi, 10, 30);
    lv_label_set_text(labelWifi, "WIFI");
    lv_obj_set_style_text_color(labelWifi, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelWifi, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelWifiValue = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(s_LabelWifiValue, 72, 30);
    lv_obj_set_width(s_LabelWifiValue, 140);
    lv_label_set_long_mode(s_LabelWifiValue, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(s_LabelWifiValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelMode = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(labelMode, 10, 58);
    lv_label_set_text(labelMode, "MODE");
    lv_obj_set_style_text_color(labelMode, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelMode, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelModeValue = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(s_LabelModeValue, 72, 58);
    lv_obj_set_width(s_LabelModeValue, 140);
    lv_label_set_long_mode(s_LabelModeValue, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_color(s_LabelModeValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelModeValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelVoice = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(labelVoice, 10, 86);
    lv_label_set_text(labelVoice, "VOICE");
    lv_obj_set_style_text_color(labelVoice, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelVoice, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelVoiceValue = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(s_LabelVoiceValue, 72, 86);
    lv_obj_set_width(s_LabelVoiceValue, 140);
    lv_label_set_long_mode(s_LabelVoiceValue, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(s_LabelVoiceValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelTcp = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(labelTcp, 224, 30);
    lv_label_set_text(labelTcp, "TCP");
    lv_obj_set_style_text_color(labelTcp, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelTcp, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelTcpValue = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(s_LabelTcpValue, 284, 30);
    lv_obj_set_width(s_LabelTcpValue, 126);
    lv_label_set_long_mode(s_LabelTcpValue, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(s_LabelTcpValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelModuleA = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(labelModuleA, 224, 58);
    lv_label_set_text(labelModuleA, "MODA");
    lv_obj_set_style_text_color(labelModuleA, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelModuleA, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelModuleAValue = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(s_LabelModuleAValue, 284, 58);
    lv_obj_set_width(s_LabelModuleAValue, 126);
    lv_label_set_long_mode(s_LabelModuleAValue, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(s_LabelModuleAValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelModuleB = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(labelModuleB, 224, 86);
    lv_label_set_text(labelModuleB, "MODB");
    lv_obj_set_style_text_color(labelModuleB, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelModuleB, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelModuleBValue = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(s_LabelModuleBValue, 284, 86);
    lv_obj_set_width(s_LabelModuleBValue, 126);
    lv_label_set_long_mode(s_LabelModuleBValue, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(s_LabelModuleBValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelIpValue = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(s_LabelIpValue, 10, 118);
    lv_obj_set_width(s_LabelIpValue, 188);
    lv_label_set_long_mode(s_LabelIpValue, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_color(s_LabelIpValue, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelIpValue, &ui_font_BebasNeueFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelServerValue = lv_label_create(ui_HaScreenSecondary);
    lv_obj_set_pos(s_LabelServerValue, 210, 118);
    lv_obj_set_width(s_LabelServerValue, 206);
    lv_label_set_long_mode(s_LabelServerValue, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_color(s_LabelServerValue, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelServerValue, &ui_font_BebasNeueFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_ButtonExit = lv_btn_create(ui_HaScreenSecondary);
    lv_obj_set_size(s_ButtonExit, 40, 20);
    lv_obj_set_align(s_ButtonExit, LV_ALIGN_CENTER);
    lv_obj_set_pos(s_ButtonExit, -181, -54);
    lv_obj_set_style_bg_opa(s_ButtonExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(s_ButtonExit, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_add_event_cb(s_ButtonExit, ui_event_ButtonExitHaSecondary, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HaScreenSecondary, ui_event_HaScreenSecondary, LV_EVENT_ALL, NULL);

    ha_apply_cached_snapshot();
}

void ui_HaScreenSecondary_screen_destroy(void)
{
    if (ui_HaScreenSecondary) {
        lv_obj_del(ui_HaScreenSecondary);
    }

    ui_HaScreenSecondary = NULL;
    ui_Label4 = NULL;
    s_HaSecondaryTitle = NULL;
    s_LabelWifiValue = NULL;
    s_LabelModeValue = NULL;
    s_LabelVoiceValue = NULL;
    s_LabelTcpValue = NULL;
    s_LabelModuleAValue = NULL;
    s_LabelModuleBValue = NULL;
    s_LabelIpValue = NULL;
    s_LabelServerValue = NULL;
    s_ButtonExit = NULL;
}