// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdbool.h>
#include <stdint.h>

lv_obj_t * ui_HaScreen = NULL;
lv_obj_t * ui_ButtonLeft4 = NULL;
lv_obj_t * ui_ButtonRight4 = NULL;
lv_obj_t * ui_ButtonEnter4 = NULL;
lv_obj_t * ui_ButtonExit4 = NULL;
static lv_obj_t * s_HaIcon = NULL;
static lv_style_t s_ha_icon_style;
static bool s_ha_icon_style_ready = false;
static lv_style_t s_ha_title_style;
static bool s_ha_title_style_ready = false;

static void ha_forward_key(uint32_t key)
{
    lv_obj_t *active_screen = lv_scr_act();
    lv_group_t *g = lv_group_get_default();
    lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;
    if (target) {
        lv_event_send(target, LV_EVENT_KEY, (void *)key);
    }
}

void ui_event_HaScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code != LV_EVENT_KEY) {
        return;
    }

    uintptr_t key = (uintptr_t)lv_event_get_param(e);
    if (key == (uintptr_t)LV_KEY_RIGHT) {
        ui_set_active_screen_tag(UI_SCREEN_SETTING);
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingScreen_screen_init);
        lv_refr_now(NULL);
    }
    else if (key == (uintptr_t)LV_KEY_LEFT) {
        ui_set_active_screen_tag(UI_SCREEN_PC_STATUS);
        _ui_screen_change(&ui_PcStatusScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_PcStatusScreen_screen_init);
        lv_refr_now(NULL);
    }
    else if (key == (uintptr_t)LV_KEY_ENTER) {
        ui_set_active_screen_tag(UI_SCREEN_HA_SECONDARY);
        _ui_screen_change(&ui_HaScreenSecondary, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HaScreenSecondary_screen_init);
        lv_refr_now(NULL);
    }
}

void ui_event_ButtonLeft4(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        ha_forward_key(LV_KEY_LEFT);
    }
}

void ui_event_ButtonRight4(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        ha_forward_key(LV_KEY_RIGHT);
    }
}

void ui_event_ButtonEnter4(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        ha_forward_key(LV_KEY_ENTER);
    }
}

void ui_HaScreen_screen_init(void)
{
    ui_set_active_screen_tag(UI_SCREEN_HA);
    ui_HaScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HaScreen, LV_OBJ_FLAG_SCROLLABLE);
    ui_set_active_screen_tag(UI_SCREEN_HA);

    if (!s_ha_icon_style_ready) {
        lv_style_init(&s_ha_icon_style);
        lv_style_set_text_font(&s_ha_icon_style, &lv_font_montserrat_48);
        s_ha_icon_style_ready = true;
    }

    if (!s_ha_title_style_ready) {
        lv_style_init(&s_ha_title_style);
        lv_style_set_text_font(&s_ha_title_style, &ui_font_FontCKJGT28);
        lv_style_set_text_letter_space(&s_ha_title_style, 1);
        lv_style_set_text_color(&s_ha_title_style, lv_color_hex(0xF5F8FF));
        lv_style_set_text_opa(&s_ha_title_style, LV_OPA_COVER);
        s_ha_title_style_ready = true;
    }

    ui_ButtonLeft4 = lv_btn_create(ui_HaScreen);
    lv_obj_set_width(ui_ButtonLeft4, 41);
    lv_obj_set_height(ui_ButtonLeft4, 28);
    lv_obj_set_x(ui_ButtonLeft4, -178);
    lv_obj_set_y(ui_ButtonLeft4, -9);
    lv_obj_set_align(ui_ButtonLeft4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLeft4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ButtonLeft4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_ButtonLeft4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLeft4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRight4 = lv_btn_create(ui_HaScreen);
    lv_obj_set_width(ui_ButtonRight4, 41);
    lv_obj_set_height(ui_ButtonRight4, 28);
    lv_obj_set_x(ui_ButtonRight4, 181);
    lv_obj_set_y(ui_ButtonRight4, -10);
    lv_obj_set_align(ui_ButtonRight4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRight4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ButtonRight4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_ButtonRight4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRight4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEnter4 = lv_btn_create(ui_HaScreen);
    lv_obj_set_width(ui_ButtonEnter4, 41);
    lv_obj_set_height(ui_ButtonEnter4, 28);
    lv_obj_set_x(ui_ButtonEnter4, 2);
    lv_obj_set_y(ui_ButtonEnter4, 38);
    lv_obj_set_align(ui_ButtonEnter4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEnter4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ButtonEnter4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_ButtonEnter4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEnter4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonExit4 = lv_btn_create(ui_HaScreen);
    lv_obj_set_width(ui_ButtonExit4, 40);
    lv_obj_set_height(ui_ButtonExit4, 20);
    lv_obj_set_x(ui_ButtonExit4, -181);
    lv_obj_set_y(ui_ButtonExit4, -54);
    lv_obj_set_align(ui_ButtonExit4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonExit4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ButtonExit4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_ButtonExit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonExit4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_HaIcon = lv_img_create(ui_HaScreen);
    lv_img_set_src(s_HaIcon, LV_SYMBOL_HOME);
    lv_obj_add_style(s_HaIcon, &s_ha_icon_style, 0);
    lv_obj_set_width(s_HaIcon, 80);
    lv_obj_set_height(s_HaIcon, 80);
    lv_obj_set_x(s_HaIcon, 20);
    lv_obj_set_y(s_HaIcon, -2);
    lv_obj_set_align(s_HaIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(s_HaIcon, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(s_HaIcon, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *ha_title = lv_label_create(ui_HaScreen);
    lv_label_set_recolor(ha_title, true);
    lv_label_set_text(ha_title, "HOME ASSISTANT");
    lv_obj_set_width(ha_title, 300);
    lv_label_set_long_mode(ha_title, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_align(ha_title, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_add_style(ha_title, &s_ha_title_style, 0);
    lv_obj_align_to(ha_title, s_HaIcon, LV_ALIGN_OUT_BOTTOM_MID, -16, -22);

    lv_obj_add_event_cb(ui_ButtonLeft4, ui_event_ButtonLeft4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRight4, ui_event_ButtonRight4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonEnter4, ui_event_ButtonEnter4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HaScreen, ui_event_HaScreen, LV_EVENT_ALL, NULL);
}

void ui_HaScreen_screen_destroy(void)
{
    if (ui_HaScreen) {
        lv_obj_del(ui_HaScreen);
    }

    ui_HaScreen = NULL;
    ui_ButtonLeft4 = NULL;
    ui_ButtonRight4 = NULL;
    ui_ButtonEnter4 = NULL;
    ui_ButtonExit4 = NULL;
    s_HaIcon = NULL;
}