// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_MainScreen_set_work_mode(char *mode);
extern void ui_MainScreen_set_rgb_light(char *value);
extern void ui_MainScreen_set_tft_light(char *value); 
extern void ui_MainScreen_set_host_connection(bool connected);
extern void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern void ui_event_ButtonLeft1(lv_event_t * e);
extern lv_obj_t * ui_ButtonLeft1;
extern void ui_event_ButtonRight1(lv_event_t * e);
extern lv_obj_t * ui_ButtonRight1;
extern lv_obj_t * ui_ButtonEnter1;
extern lv_obj_t * ui_ButtonExit1;
extern lv_obj_t * ui_ImageHome;
extern lv_obj_t * ui_ImageVolume;
extern lv_obj_t * ui_ImageWifi;
extern lv_obj_t * ui_ImagePower;
extern lv_obj_t * ui_ImageWorkmode;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_LabelData;
extern lv_obj_t * ui_LabelSecond;
extern lv_obj_t * ui_LabelWeek;
extern lv_obj_t * ui_LabelKeyboard;
extern lv_obj_t * ui_LabelWorkmode;
extern lv_obj_t * ui_LabelModA;
extern lv_obj_t * ui_LabelModB;
extern lv_obj_t * ui_LabelRGBLight;
extern lv_obj_t * ui_LabelTFTLight;
extern lv_obj_t * ui_ImageModA;
extern lv_obj_t * ui_ImageModB;
extern lv_obj_t * ui_line1;
extern lv_obj_t * ui_line2;
extern lv_obj_t * ui_line3;
extern lv_obj_t * ui_line4;
extern lv_obj_t * ui_line5;
extern lv_obj_t * ui_line6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
