// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_MusicScreen = NULL;
lv_obj_t * ui_ButtonLeft2 = NULL;
lv_obj_t * ui_ButtonRight2 = NULL;
lv_obj_t * ui_ButtonEnter2 = NULL;
lv_obj_t * ui_ButtonExit2 = NULL;
lv_obj_t * ui_Label7 = NULL;
static lv_obj_t * ui_MusicIcon = NULL;
static lv_obj_t * s_music_visual_host = NULL;
static lv_style_t s_music_icon_style;
static bool s_music_icon_style_ready = false;
static lv_style_t s_music_title_style;
static bool s_music_title_style_ready = false;
static lv_obj_t * s_music_visual_ambience = NULL;

static void music_reset_visual_state(void);

static void music_forward_key(uint32_t key)
{
    lv_obj_t *active_screen = lv_scr_act();
    lv_group_t *g = lv_group_get_default();
    lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;
    if (target) {
        lv_event_send(target, LV_EVENT_KEY, (void *)key);
    }
}

void ui_MusicScreen_set_visual_host(lv_obj_t *host)
{
    if (s_music_visual_host == host) {
        return;
    }

    music_reset_visual_state();
    s_music_visual_host = host;
}

// event funtions
void ui_event_MusicScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    uintptr_t key = (uintptr_t)lv_event_get_param(e);

    if(event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_RIGHT) {
        ui_set_active_screen_tag(UI_SCREEN_PC_STATUS);
        _ui_screen_change(&ui_PcStatusScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_PcStatusScreen_screen_init);
        lv_refr_now(NULL);
    }
    else if(event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_LEFT) {
        ui_set_active_screen_tag(UI_SCREEN_KEYMAPPED);
        _ui_screen_change(&ui_KeyMapped, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_KeyMapped_screen_init);
        lv_refr_now(NULL);        
    }
    else if(event_code == LV_EVENT_KEY && key == (uintptr_t)LV_KEY_ENTER) {
        ui_set_active_screen_tag(UI_SCREEN_MUSIC_SECONDARY);
        _ui_screen_change(&ui_MusicScreenSecondary, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MusicScreenSecondary_screen_init);
        lv_refr_now(NULL);
    }
}

void ui_event_ButtonLeft2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // 获取当前屏幕及其聚焦对象
        lv_obj_t *active_screen = lv_scr_act();
        lv_group_t *g = lv_group_get_default();
        lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;

        // 发送按键事件
        if (target) {
            lv_event_send(target, LV_EVENT_KEY, (void *)LV_KEY_LEFT);
        }
    }
}

void ui_event_ButtonRight2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // 获取当前屏幕及其聚焦对象
        lv_obj_t *active_screen = lv_scr_act();
        lv_group_t *g = lv_group_get_default();
        lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;

        // 发送按键事件
        if (target) {
            lv_event_send(target, LV_EVENT_KEY, (void *)LV_KEY_RIGHT);
        }
    }
}

void ui_event_ButtonEnter2(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        music_forward_key(LV_KEY_ENTER);
    }
}

// build funtions

#define SCREEN_WIDTH  428
#define SCREEN_HEIGHT 142
#define BAND_COUNT    16

#define BAR_FALL_FACTOR     2     // 柱子回落惯性
#define PEAK_FOLLOW_FACTOR  3     // 峰值贴合速度（越小越贴）
#define PEAK_MIN_FALL       2     // 峰值最小下降像素

static int barHeights[BAND_COUNT]  = {0};
static int peakHeights[BAND_COUNT] = {0};
static int barTargets[BAND_COUNT]  = {0};
int offsetX = 5;

static lv_obj_t* barRails[BAND_COUNT] = { NULL};
static lv_obj_t* bars[BAND_COUNT] = { NULL};
static lv_obj_t* peaks[BAND_COUNT] = { NULL };

static void music_reset_visual_state(void)
{
    s_music_visual_ambience = NULL;
    for (int i = 0; i < BAND_COUNT; ++i) {
        barRails[i] = NULL;
        bars[i] = NULL;
        peaks[i] = NULL;
        barHeights[i] = 0;
        peakHeights[i] = 0;
        barTargets[i] = 0;
    }
}


//电音 / 科技蓝紫 效果
// static lv_color_t getBarColor(int h)
// {
//     float t = (float)h / SCREEN_HEIGHT;
//     t = LV_CLAMP(0.0f, t, 1.0f);

//     uint8_t r = (uint8_t)(60  + 120 * t);
//     uint8_t g = (uint8_t)(40  +  60 * t);
//     uint8_t b = (uint8_t)(180 +  60 * t);

//     return lv_color_make(r, g, b);
// }

// static lv_color_t getPeakColor(int h)
// {
//     LV_UNUSED(h);
//     return lv_color_make(255, 80, 180); // Neon Pink
// }

// //夜店电音绿 效果（能量感最强）
// static lv_color_t getBarColor(int h)
// {
//     float t = (float)h / SCREEN_HEIGHT;
//     t = LV_CLAMP(0.0f, t, 1.0f);

//     uint8_t r = 40;
//     uint8_t g = (uint8_t)(100 + 155 * t);
//     uint8_t b = 60;

//     return lv_color_make(r, g, b);
// }

// static lv_color_t getPeakColor(int h)
// {
//     LV_UNUSED(h);
//     return lv_color_make(180, 255, 120);
// }

// 与当前音乐页一致的冷蓝基底 + 暖红峰值风格
static lv_color_t getBarColor(int h)
{
    float t = (float)h / SCREEN_HEIGHT;
    t = LV_CLAMP(0.0f, t, 1.0f);

    const uint8_t r = (uint8_t)(68 + 143 * t);
    const uint8_t g = (uint8_t)(92 + 38 * t);
    const uint8_t b = (uint8_t)(118 - 38 * t);
    return lv_color_make(r, g, b);
}

static lv_color_t getBarBaseColor(int h)
{
    float t = (float)h / SCREEN_HEIGHT;
    t = LV_CLAMP(0.0f, t, 1.0f);

    const uint8_t r = (uint8_t)(20 + 40 * t);
    const uint8_t g = (uint8_t)(31 + 34 * t);
    const uint8_t b = (uint8_t)(44 + 26 * t);
    return lv_color_make(r, g, b);
}

static lv_color_t getPeakColor(int h)
{
    float t = (float)h / SCREEN_HEIGHT;
    t = LV_CLAMP(0.0f, t, 1.0f);

    const uint8_t r = (uint8_t)(214 + 28 * t);
    const uint8_t g = (uint8_t)(58 + 56 * t);
    const uint8_t b = (uint8_t)(49 + 36 * t);
    return lv_color_make(r, g, b);
}

static lv_color_t getPeakGlowColor(int h)
{
    float t = (float)h / SCREEN_HEIGHT;
    t = LV_CLAMP(0.0f, t, 1.0f);

    const uint8_t r = (uint8_t)(255);
    const uint8_t g = (uint8_t)(142 + 40 * t);
    const uint8_t b = (uint8_t)(120 + 24 * t);
    return lv_color_make(r, g, b);
}


void ui_MusicScreen_drawAudioBandsCool(const float* bands) {
    if (!s_music_visual_host) {
        return;
    }

    const int hostWidth = lv_obj_get_content_width(s_music_visual_host);
    const int hostHeight = lv_obj_get_content_height(s_music_visual_host);
    const int visualMaxHeight = LV_MAX(8, (hostHeight * 9) / 10);
    const int columnWidth = LV_MAX(1, hostWidth / BAND_COUNT);
    const int leftPadding = LV_MAX(0, (hostWidth - (columnWidth * BAND_COUNT)) / 2);
    const int railWidth = LV_MAX(1, columnWidth - 10);
    const int barWidth = LV_MAX(1, railWidth);
    const int barOffset = (columnWidth - barWidth) / 2;
    const int railOffset = (columnWidth - railWidth) / 2;

    if (!s_music_visual_ambience) {
        s_music_visual_ambience = lv_obj_create(s_music_visual_host);
        lv_obj_set_size(s_music_visual_ambience, hostWidth, hostHeight);
        lv_obj_align(s_music_visual_ambience, LV_ALIGN_BOTTOM_MID, 0, 0);
        lv_obj_clear_flag(s_music_visual_ambience, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_radius(s_music_visual_ambience, 0, 0);
        lv_obj_set_style_border_width(s_music_visual_ambience, 0, 0);
        lv_obj_set_style_pad_all(s_music_visual_ambience, 0, 0);
        lv_obj_set_style_bg_opa(s_music_visual_ambience, LV_OPA_TRANSP, 0);
        lv_obj_set_style_shadow_width(s_music_visual_ambience, 0, 0);
        lv_obj_set_style_shadow_opa(s_music_visual_ambience, LV_OPA_TRANSP, 0);
        lv_obj_move_background(s_music_visual_ambience);
    } else {
        lv_obj_set_size(s_music_visual_ambience, hostWidth, hostHeight);
        lv_obj_align(s_music_visual_ambience, LV_ALIGN_BOTTOM_MID, 0, 0);
    }

    for (int i = 0; i < BAND_COUNT; i++) {

        // bands: 0~255
        int boostedBand = (int)(bands[i] * 2.0f);
        if (boostedBand > 255) {
            boostedBand = 255;
        }
        if (boostedBand < 0) {
            boostedBand = 0;
        }
        barTargets[i] = lv_map(boostedBand, 0, 255, 3, visualMaxHeight);

        /* ---------- 下落拖尾平滑 ---------- */
        if (barTargets[i] < barHeights[i]) {
            barHeights[i] -= (barHeights[i] - barTargets[i]) / BAR_FALL_FACTOR;
        } else {
            barHeights[i] += (barTargets[i] - barHeights[i]) / 2;
        }

        if (barHeights[i] < 2) {
            barHeights[i] = 2;
        }

        if (!barRails[i]) {
            barRails[i] = lv_obj_create(s_music_visual_host);
            lv_obj_set_size(barRails[i], railWidth, hostHeight);
            lv_obj_clear_flag(barRails[i], LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_radius(barRails[i], 0, 0);
            lv_obj_set_style_bg_color(barRails[i], lv_color_hex(0x192028), 0);
            lv_obj_set_style_bg_opa(barRails[i], 42, 0);
            lv_obj_set_style_border_width(barRails[i], 1, 0);
            lv_obj_set_style_border_color(barRails[i], lv_color_hex(0x293545), 0);
            lv_obj_set_style_border_opa(barRails[i], 28, 0);
            lv_obj_set_style_pad_all(barRails[i], 0, 0);
            lv_obj_set_style_shadow_width(barRails[i], 0, 0);
        }

        lv_obj_align(barRails[i], LV_ALIGN_TOP_LEFT, leftPadding + i * columnWidth + railOffset, 0);

        /* ---------- 瀑布拖尾 ---------- */
        if (!bars[i]) {
            bars[i] = lv_obj_create(s_music_visual_host);
            lv_obj_set_style_radius(bars[i], 0, 0);
            lv_obj_set_width(bars[i], barWidth);
            lv_obj_clear_flag(bars[i], LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_border_width(bars[i], 0, 0);
            lv_obj_set_style_pad_all(bars[i], 0, 0);
            lv_obj_set_style_bg_grad_dir(bars[i], LV_GRAD_DIR_VER, 0);
            lv_obj_set_style_bg_main_stop(bars[i], 0, 0);
            lv_obj_set_style_bg_grad_stop(bars[i], 255, 0);
            lv_obj_set_style_shadow_width(bars[i], 3, 0);
            lv_obj_set_style_shadow_spread(bars[i], 0, 0);
        }

        lv_obj_set_height(bars[i], barHeights[i]);
        lv_obj_align(bars[i], LV_ALIGN_TOP_LEFT, leftPadding + i * columnWidth + barOffset, 0);
        lv_obj_set_style_bg_color(bars[i], getBarColor(barHeights[i]), 0);
        lv_obj_set_style_bg_grad_color(bars[i], lv_color_hex(0x0B1017), 0);
        lv_obj_set_style_bg_opa(bars[i], 170, 0);
        lv_obj_set_style_shadow_color(bars[i], getBarColor(barHeights[i]), 0);
        lv_obj_set_style_shadow_opa(bars[i], 28, 0);
        if (peaks[i]) {
            lv_obj_add_flag(peaks[i], LV_OBJ_FLAG_HIDDEN);
        }
    }
}



// // 缓存条高度，实现平滑衰减
// static int barHeights[BAND_COUNT] = {0};
// static int barTargets[BAND_COUNT] = {0};

// // 渐变色函数，根据高度返回颜色
// static lv_color_t getBarColor(int height) {
//     uint8_t r = lv_map(height, 0, SCREEN_HEIGHT, 0, 255);
//     uint8_t g = lv_map(height, 0, SCREEN_HEIGHT, 255, 50);
//     uint8_t b = 50;
//     return lv_color_make(r, g, b);
// }

// // 绘制或更新频谱
// void ui_MusicScreen_drawAudioBandsCool(const float* bands) {
//     static lv_obj_t* bars[BAND_COUNT] = { NULL };
//     int barWidth = SCREEN_WIDTH / BAND_COUNT;

//     for (int i = 0; i < BAND_COUNT; i++) {
//         // 映射 0~255 到屏幕高度
//         barTargets[i] = (int)((bands[i] / 255.0f) * SCREEN_HEIGHT);

//         // 平滑衰减：如果目标比当前低，则慢慢下降
//         if (barTargets[i] < barHeights[i]) {
//             barHeights[i] -= (barHeights[i] - barTargets[i]) / 4; // 衰减速度可调
//         } else {
//             barHeights[i] = barTargets[i]; // 直接更新高度
//         }

//         if (!bars[i]) {
//             // 第一次创建条
//             bars[i] = lv_obj_create(ui_MusicScreen);
//             lv_obj_set_size(bars[i], barWidth - 2, barHeights[i]);
//             lv_obj_set_style_radius(bars[i], 0, 0);
//             lv_obj_align(bars[i], LV_ALIGN_BOTTOM_LEFT, i * barWidth, 0);
//         } else {
//             lv_obj_set_height(bars[i], barHeights[i]);
//         }

//         // 设置渐变色
//         lv_obj_set_style_bg_color(bars[i], getBarColor(barHeights[i]), 0);
//     }
// }

// 绘制频谱条形图
void ui_MusicScreen_drawAudioBands(const float* bands) {
    if (!s_music_visual_host) {
        return;
    }

    // 计算每条柱子的宽度和间距
    const int hostWidth = lv_obj_get_content_width(s_music_visual_host);
    const int barWidth  = LV_MAX(1, hostWidth / BAND_COUNT);
    const int maxHeight = lv_obj_get_content_height(s_music_visual_host);
    const int leftPadding = LV_MAX(0, (hostWidth - (barWidth * BAND_COUNT)) / 2);

    for (int i = 0; i < BAND_COUNT; i++) {
        int barHeight = (int)((bands[i] / 255.0f) * maxHeight);

        if (!bars[i]) {
            // 第一次创建对象
            bars[i] = lv_obj_create(s_music_visual_host);
            lv_obj_set_size(bars[i], barWidth - 2, barHeight); // 留一点间隙
            lv_obj_set_style_bg_color(bars[i], lv_color_make(0, 255, 0), 0);
            lv_obj_set_style_radius(bars[i], 0, 0);
            lv_obj_set_style_border_width(bars[i], 0, 0);
            lv_obj_set_style_pad_all(bars[i], 0, 0);
            lv_obj_clear_flag(bars[i], LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_align(bars[i], LV_ALIGN_BOTTOM_LEFT, leftPadding + i * barWidth, 0);
        } else {
            // 更新高度
            lv_obj_set_height(bars[i], barHeight);
            lv_obj_align(bars[i], LV_ALIGN_BOTTOM_LEFT, leftPadding + i * barWidth, 0);
        }
    }
}


void ui_MusicScreen_screen_init(void)
{
    ui_MusicScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MusicScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_set_active_screen_tag(UI_SCREEN_MUSIC);

    ui_ButtonLeft2 = lv_btn_create(ui_MusicScreen);
    lv_obj_set_width(ui_ButtonLeft2, 41);
    lv_obj_set_height(ui_ButtonLeft2, 28);
    lv_obj_set_x(ui_ButtonLeft2, -178);
    lv_obj_set_y(ui_ButtonLeft2, -9);
    lv_obj_set_align(ui_ButtonLeft2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLeft2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLeft2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLeft2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLeft2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRight2 = lv_btn_create(ui_MusicScreen);
    lv_obj_set_width(ui_ButtonRight2, 41);
    lv_obj_set_height(ui_ButtonRight2, 28);
    lv_obj_set_x(ui_ButtonRight2, 181);
    lv_obj_set_y(ui_ButtonRight2, -10);
    lv_obj_set_align(ui_ButtonRight2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRight2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRight2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRight2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRight2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEnter2 = lv_btn_create(ui_MusicScreen);
    lv_obj_set_width(ui_ButtonEnter2, 41);
    lv_obj_set_height(ui_ButtonEnter2, 28);
    lv_obj_set_x(ui_ButtonEnter2, 2);
    lv_obj_set_y(ui_ButtonEnter2, 38);
    lv_obj_set_align(ui_ButtonEnter2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEnter2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEnter2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonEnter2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEnter2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonExit2 = lv_btn_create(ui_MusicScreen);
    lv_obj_set_width(ui_ButtonExit2, 40);
    lv_obj_set_height(ui_ButtonExit2, 20);
    lv_obj_set_x(ui_ButtonExit2, -181);
    lv_obj_set_y(ui_ButtonExit2, -54);
    lv_obj_set_align(ui_ButtonExit2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonExit2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonExit2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonExit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonExit2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    if (!s_music_icon_style_ready) {
        lv_style_init(&s_music_icon_style);
        lv_style_set_text_font(&s_music_icon_style, &lv_font_montserrat_48);
        s_music_icon_style_ready = true;
    }

    if (!s_music_title_style_ready) {
        lv_style_init(&s_music_title_style);
        lv_style_set_text_font(&s_music_title_style, &ui_font_FontCKJGT28);
        lv_style_set_text_letter_space(&s_music_title_style, 1);
        lv_style_set_text_color(&s_music_title_style, lv_color_hex(0xF5F8FF));
        lv_style_set_text_opa(&s_music_title_style, LV_OPA_COVER);
        s_music_title_style_ready = true;
    }

    ui_MusicIcon = lv_img_create(ui_MusicScreen);
    lv_img_set_src(ui_MusicIcon, LV_SYMBOL_AUDIO);
    lv_obj_add_style(ui_MusicIcon, &s_music_icon_style, 0);
    lv_obj_set_width(ui_MusicIcon, 80);
    lv_obj_set_height(ui_MusicIcon, 80);
    lv_obj_set_x(ui_MusicIcon, 20);
    lv_obj_set_y(ui_MusicIcon, -2);
    lv_obj_set_align(ui_MusicIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MusicIcon, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_MusicIcon, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *music_title = lv_label_create(ui_MusicScreen);
    lv_label_set_recolor(music_title, true);
    lv_label_set_text(music_title, "MUSIC CONTROLER");
    lv_obj_set_width(music_title, 300);
    lv_label_set_long_mode(music_title, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_align(music_title, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_add_style(music_title, &s_music_title_style, 0);
    lv_obj_align_to(music_title, ui_MusicIcon, LV_ALIGN_OUT_BOTTOM_MID, -16, -22);

    ui_Label7 = lv_label_create(ui_MusicScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, -5);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "MusicScreen");
    lv_obj_add_flag(ui_Label7, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_ButtonLeft2, ui_event_ButtonLeft2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRight2, ui_event_ButtonRight2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonEnter2, ui_event_ButtonEnter2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MusicScreen, ui_event_MusicScreen, LV_EVENT_ALL, NULL);

}

void ui_MusicScreen_screen_destroy(void)
{
    if(ui_MusicScreen) lv_obj_del(ui_MusicScreen);

    // NULL screen variables
    ui_MusicScreen = NULL;
    ui_ButtonLeft2 = NULL;
    ui_ButtonRight2 = NULL;
    ui_ButtonEnter2 = NULL;
    ui_ButtonExit2 = NULL;
    ui_Label7 = NULL;
    ui_MusicIcon = NULL;

}
