// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

lv_obj_t * ui_PcStatusScreenSecondary = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_LabelPcHost = NULL;
lv_obj_t * ui_LabelPcTime = NULL;
lv_obj_t * ui_LabelPcLocks = NULL;
lv_obj_t * ui_LabelPcNetwork = NULL;
lv_obj_t * ui_LabelPcPower = NULL;
static lv_obj_t * s_LabelPcPerf = NULL;
static lv_obj_t * s_LabelPcTemp = NULL;

static lv_obj_t * s_PanelLeft = NULL;
static lv_obj_t * s_PanelRight = NULL;
static lv_obj_t * s_LabelTimeValue = NULL;
static lv_obj_t * s_LabelNetValue = NULL;
static lv_obj_t * s_LabelUpValue = NULL;
static lv_obj_t * s_LabelDownValue = NULL;
static lv_obj_t * s_LabelCpuValue = NULL;
static lv_obj_t * s_LabelCpuTempValue = NULL;
static lv_obj_t * s_LabelMemValue = NULL;
static lv_obj_t * s_LabelDiskValue = NULL;
static lv_obj_t * s_NetDot = NULL;
static lv_obj_t * s_BarCpu = NULL;
static lv_obj_t * s_BarCpuTemp = NULL;
static lv_obj_t * s_BarMem = NULL;
static lv_obj_t * s_BarDisk = NULL;
static lv_obj_t * s_ButtonLeft = NULL;
static lv_obj_t * s_ButtonRight = NULL;
static lv_obj_t * s_ButtonEnter = NULL;
static lv_obj_t * s_ButtonExit = NULL;

static char s_HostStatusText[64] = "";
static char s_TimeStatusText[64] = "";
static char s_LockStatusText[64] = "";
static char s_NetworkStatusText[64] = "";
static char s_PowerStatusText[64] = "";
static char s_CpuTempStatusText[64] = "";
static char s_PerfStatusText[64] = "";
static char s_TempStatusText[64] = "";

static void pc_status_cache_text(char *buffer, size_t buffer_size, const char *text)
{
    if (!buffer || buffer_size == 0) {
        return;
    }

    snprintf(buffer, buffer_size, "%s", text ? text : "");
}

static void extract_value_part(const char *text, char *out, size_t outSize)
{
    if (!out || outSize == 0) return;
    out[0] = '\0';
    if (!text) return;

    const char *sep = strchr(text, ':');
    if (!sep) {
        snprintf(out, outSize, "%s", text);
        return;
    }

    const char *value = sep + 1;
    while (*value == ' ') value++;
    snprintf(out, outSize, "%s", value);
}

static int extract_percent_value(const char *text)
{
    if (!text) return -1;

    const char *p = text;
    while (*p && !((*p >= '0' && *p <= '9') || *p == '-')) p++;
    if (!*p) return -1;

    float v = strtof(p, NULL);
    if (v < 0.0f) return -1;
    if (v > 100.0f) v = 100.0f;
    return (int)(v + 0.5f);
}

static void pc_status_set_bar_value(lv_obj_t *bar, int value)
{
    if (!bar) {
        return;
    }

    if (value < 0) {
        lv_bar_set_value(bar, 0, LV_ANIM_OFF);
    } else {
        lv_bar_set_value(bar, value, LV_ANIM_ON);
    }
}

static void pc_status_apply_cached_values(void)
{
    ui_PcStatusScreen_set_host_status(s_HostStatusText[0] ? s_HostStatusText : NULL);
    ui_PcStatusScreen_set_time_status(s_TimeStatusText[0] ? s_TimeStatusText : NULL);
    ui_PcStatusScreen_set_lock_status(s_LockStatusText[0] ? s_LockStatusText : NULL);
    ui_PcStatusScreen_set_network_status(s_NetworkStatusText[0] ? s_NetworkStatusText : NULL);
    ui_PcStatusScreen_set_power_status(s_PowerStatusText[0] ? s_PowerStatusText : NULL);
    ui_PcStatusScreen_set_cpu_temp_status(s_CpuTempStatusText[0] ? s_CpuTempStatusText : NULL);
    ui_PcStatusScreen_set_perf_status(s_PerfStatusText[0] ? s_PerfStatusText : NULL);
    ui_PcStatusScreen_set_temp_status(s_TempStatusText[0] ? s_TempStatusText : NULL);
}

static void pc_status_secondary_forward_key(uint32_t key)
{
    lv_obj_t *active_screen = lv_scr_act();
    lv_group_t *g = lv_group_get_default();
    lv_obj_t *target = g ? lv_group_get_focused(g) : active_screen;
    if (target) {
        lv_event_send(target, LV_EVENT_KEY, (void *)key);
    }
}

void ui_PcStatusScreen_set_host_status(const char *text)
{
    char value[32] = {0};
    pc_status_cache_text(s_HostStatusText, sizeof(s_HostStatusText), text);
    if (!s_LabelTimeValue) return;

    extract_value_part(text, value, sizeof(value));
    lv_label_set_text(s_LabelTimeValue, value[0] ? value : "--:--:--");
}

void ui_PcStatusScreen_set_time_status(const char *text)
{
    char value[24] = {0};
    pc_status_cache_text(s_TimeStatusText, sizeof(s_TimeStatusText), text);
    if (!s_LabelNetValue || !s_NetDot) return;

    extract_value_part(text, value, sizeof(value));
    lv_label_set_text(s_LabelNetValue, value[0] ? value : "OFFLINE");

    lv_obj_set_style_bg_color(s_NetDot,
                              strstr(value, "ONLINE") != NULL ? lv_color_hex(0x22C55E) : lv_color_hex(0xEF4444),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_PcStatusScreen_set_lock_status(const char *text)
{
    char value[32] = {0};
    pc_status_cache_text(s_LockStatusText, sizeof(s_LockStatusText), text);
    if (!s_LabelUpValue) return;

    extract_value_part(text, value, sizeof(value));
    lv_label_set_text(s_LabelUpValue, value[0] ? value : "-- Kbps");
}

void ui_PcStatusScreen_set_network_status(const char *text)
{
    char value[32] = {0};
    pc_status_cache_text(s_NetworkStatusText, sizeof(s_NetworkStatusText), text);
    if (!s_LabelDownValue) return;

    extract_value_part(text, value, sizeof(value));
    lv_label_set_text(s_LabelDownValue, value[0] ? value : "-- Kbps");
}

void ui_PcStatusScreen_set_power_status(const char *text)
{
    char value[24] = {0};
    pc_status_cache_text(s_PowerStatusText, sizeof(s_PowerStatusText), text);
    if (!s_LabelCpuValue || !s_BarCpu) return;

    extract_value_part(text, value, sizeof(value));
    lv_label_set_text(s_LabelCpuValue, value[0] ? value : "--");
    pc_status_set_bar_value(s_BarCpu, extract_percent_value(value));
}

void ui_PcStatusScreen_set_cpu_temp_status(const char *text)
{
    char value[24] = {0};
    pc_status_cache_text(s_CpuTempStatusText, sizeof(s_CpuTempStatusText), text);
    if (!s_LabelCpuTempValue) return;

    extract_value_part(text, value, sizeof(value));
    lv_label_set_text(s_LabelCpuTempValue, value[0] ? value : "N/A");
    pc_status_set_bar_value(s_BarCpuTemp, extract_percent_value(value));
}

void ui_PcStatusScreen_set_perf_status(const char *text)
{
    char value[24] = {0};
    pc_status_cache_text(s_PerfStatusText, sizeof(s_PerfStatusText), text);
    if (!s_LabelMemValue || !s_BarMem) return;

    extract_value_part(text, value, sizeof(value));
    lv_label_set_text(s_LabelMemValue, value[0] ? value : "--");
    pc_status_set_bar_value(s_BarMem, extract_percent_value(value));
}

void ui_PcStatusScreen_set_temp_status(const char *text)
{
    char value[24] = {0};
    pc_status_cache_text(s_TempStatusText, sizeof(s_TempStatusText), text);
    if (!s_LabelDiskValue || !s_BarDisk) return;

    extract_value_part(text, value, sizeof(value));
    lv_label_set_text(s_LabelDiskValue, value[0] ? value : "--");
    pc_status_set_bar_value(s_BarDisk, extract_percent_value(value));
}

void ui_event_PcStatusScreenSecondary(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_KEY) {
        return;
    }

    if ((uintptr_t)lv_event_get_param(e) == (uintptr_t)LV_KEY_ESC) {
        ui_set_active_screen_tag(UI_SCREEN_PC_STATUS);
        _ui_screen_change(&ui_PcStatusScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_PcStatusScreen_screen_init);
        lv_refr_now(NULL);
    }
}

void ui_event_ButtonExitPcStatusSecondary(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        pc_status_secondary_forward_key(LV_KEY_ESC);
    }
}

void ui_PcStatusScreenSecondary_screen_init(void)
{
    ui_PcStatusScreenSecondary = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PcStatusScreenSecondary, LV_OBJ_FLAG_SCROLLABLE);

    ui_Label2 = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "PC STATUS");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x6ADAE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_PanelLeft = NULL;
    s_PanelRight = NULL;

    lv_obj_t *labelTime = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelTime, 10, 26);
    lv_label_set_text(labelTime, "TIME");
    lv_obj_set_style_text_color(labelTime, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelTime, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelTimeValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelTimeValue, 76, 26);
    lv_obj_set_width(s_LabelTimeValue, 150);
    lv_label_set_long_mode(s_LabelTimeValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelTimeValue, "--:--:--");
    lv_obj_set_style_text_color(s_LabelTimeValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelTimeValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelNet = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelNet, 10, 50);
    lv_label_set_text(labelNet, "NET");
    lv_obj_set_style_text_color(labelNet, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelNet, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_NetDot = lv_obj_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_NetDot, 10, 10);
    lv_obj_set_pos(s_NetDot, 56, 56);
    lv_obj_set_style_radius(s_NetDot, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_NetDot, lv_color_hex(0xEF4444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(s_NetDot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelNetValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelNetValue, 76, 50);
    lv_obj_set_width(s_LabelNetValue, 144);
    lv_label_set_long_mode(s_LabelNetValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelNetValue, "OFFLINE");
    lv_obj_set_style_text_color(s_LabelNetValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelNetValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelUp = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelUp, 10, 74);
    lv_label_set_text(labelUp, "UP");
    lv_obj_set_style_text_color(labelUp, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelUp, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelUpValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelUpValue, 76, 74);
    lv_obj_set_width(s_LabelUpValue, 160);
    lv_label_set_long_mode(s_LabelUpValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelUpValue, "-- Kbps");
    lv_obj_set_style_text_color(s_LabelUpValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelUpValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelDown = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelDown, 10, 98);
    lv_label_set_text(labelDown, "DOWN");
    lv_obj_set_style_text_color(labelDown, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelDown, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelDownValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelDownValue, 76, 98);
    lv_obj_set_width(s_LabelDownValue, 160);
    lv_label_set_long_mode(s_LabelDownValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelDownValue, "-- Kbps");
    lv_obj_set_style_text_color(s_LabelDownValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelDownValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *labelCpu = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelCpu, 244, 26);
    lv_label_set_text(labelCpu, "CPU");
    lv_obj_set_style_text_color(labelCpu, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelCpu, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelCpuValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelCpuValue, 308, 26);
    lv_obj_set_width(s_LabelCpuValue, 50);
    lv_label_set_long_mode(s_LabelCpuValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelCpuValue, "--");
    lv_obj_set_style_text_color(s_LabelCpuValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelCpuValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_BarCpu = lv_bar_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_BarCpu, 60, 10);
    lv_obj_set_pos(s_BarCpu, 365, 34);
    lv_bar_set_range(s_BarCpu, 0, 100);
    lv_obj_set_style_bg_color(s_BarCpu, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_BarCpu, lv_color_hex(0x22C55E), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t *labelCpuTemp = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelCpuTemp, 244, 50);
    lv_label_set_text(labelCpuTemp, "CPU-T");
    lv_obj_set_style_text_color(labelCpuTemp, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelCpuTemp, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelCpuTempValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelCpuTempValue, 308, 50);
    lv_obj_set_width(s_LabelCpuTempValue, 70);
    lv_label_set_long_mode(s_LabelCpuTempValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelCpuTempValue, "N/A");
    lv_obj_set_style_text_color(s_LabelCpuTempValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelCpuTempValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_BarCpuTemp = lv_bar_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_BarCpuTemp, 60, 10);
    lv_obj_set_pos(s_BarCpuTemp, 365, 58);
    lv_bar_set_range(s_BarCpuTemp, 0, 100);
    lv_bar_set_value(s_BarCpuTemp, 0, LV_ANIM_OFF);
    lv_obj_set_style_bg_color(s_BarCpuTemp, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_BarCpuTemp, lv_color_hex(0xEF4444), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t *labelMem = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelMem, 244, 74);
    lv_label_set_text(labelMem, "MEM");
    lv_obj_set_style_text_color(labelMem, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelMem, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelMemValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelMemValue, 308, 74);
    lv_obj_set_width(s_LabelMemValue, 50);
    lv_label_set_long_mode(s_LabelMemValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelMemValue, "--");
    lv_obj_set_style_text_color(s_LabelMemValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelMemValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_BarMem = lv_bar_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_BarMem, 60, 10);
    lv_obj_set_pos(s_BarMem, 365, 86);
    lv_bar_set_range(s_BarMem, 0, 100);
    lv_obj_set_style_bg_color(s_BarMem, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_BarMem, lv_color_hex(0x3B82F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t *labelDisk = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(labelDisk, 244, 98);
    lv_label_set_text(labelDisk, "D-IO");
    lv_obj_set_style_text_color(labelDisk, lv_color_hex(0xFDE68A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(labelDisk, &ui_font_BebasNeueFont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_LabelDiskValue = lv_label_create(ui_PcStatusScreenSecondary);
    lv_obj_set_pos(s_LabelDiskValue, 308, 98);
    lv_obj_set_width(s_LabelDiskValue, 50);
    lv_label_set_long_mode(s_LabelDiskValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(s_LabelDiskValue, "--");
    lv_obj_set_style_text_color(s_LabelDiskValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_LabelDiskValue, &ui_font_BebasNeueFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_BarDisk = lv_bar_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_BarDisk, 60, 10);
    lv_obj_set_pos(s_BarDisk, 365, 114);
    lv_bar_set_range(s_BarDisk, 0, 100);
    lv_obj_set_style_bg_color(s_BarDisk, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_BarDisk, lv_color_hex(0xF59E0B), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelPcHost = s_LabelTimeValue;
    ui_LabelPcTime = s_LabelNetValue;
    ui_LabelPcLocks = s_LabelUpValue;
    ui_LabelPcNetwork = s_LabelDownValue;
    ui_LabelPcPower = s_LabelCpuValue;
    s_LabelPcPerf = s_LabelMemValue;
    s_LabelPcTemp = s_LabelDiskValue;

    s_ButtonLeft = lv_btn_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_ButtonLeft, 41, 28);
    lv_obj_set_align(s_ButtonLeft, LV_ALIGN_CENTER);
    lv_obj_set_pos(s_ButtonLeft, -178, -9);
    lv_obj_set_style_bg_opa(s_ButtonLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(s_ButtonLeft, LV_OBJ_FLAG_SCROLLABLE);

    s_ButtonRight = lv_btn_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_ButtonRight, 41, 28);
    lv_obj_set_align(s_ButtonRight, LV_ALIGN_CENTER);
    lv_obj_set_pos(s_ButtonRight, 181, -10);
    lv_obj_set_style_bg_opa(s_ButtonRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(s_ButtonRight, LV_OBJ_FLAG_SCROLLABLE);

    s_ButtonEnter = lv_btn_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_ButtonEnter, 41, 28);
    lv_obj_set_align(s_ButtonEnter, LV_ALIGN_CENTER);
    lv_obj_set_pos(s_ButtonEnter, 2, 38);
    lv_obj_set_style_bg_opa(s_ButtonEnter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(s_ButtonEnter, LV_OBJ_FLAG_SCROLLABLE);

    s_ButtonExit = lv_btn_create(ui_PcStatusScreenSecondary);
    lv_obj_set_size(s_ButtonExit, 40, 20);
    lv_obj_set_align(s_ButtonExit, LV_ALIGN_CENTER);
    lv_obj_set_pos(s_ButtonExit, -181, -54);
    lv_obj_set_style_bg_opa(s_ButtonExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(s_ButtonExit, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_add_event_cb(s_ButtonExit, ui_event_ButtonExitPcStatusSecondary, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PcStatusScreenSecondary, ui_event_PcStatusScreenSecondary, LV_EVENT_ALL, NULL);

    pc_status_apply_cached_values();
}

void ui_PcStatusScreenSecondary_screen_destroy(void)
{
    if (ui_PcStatusScreenSecondary) {
        lv_obj_del(ui_PcStatusScreenSecondary);
    }

    ui_PcStatusScreenSecondary = NULL;
    ui_Label2 = NULL;
    ui_LabelPcHost = NULL;
    ui_LabelPcTime = NULL;
    ui_LabelPcLocks = NULL;
    ui_LabelPcNetwork = NULL;
    ui_LabelPcPower = NULL;
    s_LabelPcPerf = NULL;
    s_LabelPcTemp = NULL;
    s_PanelLeft = NULL;
    s_PanelRight = NULL;
    s_LabelTimeValue = NULL;
    s_LabelNetValue = NULL;
    s_LabelUpValue = NULL;
    s_LabelDownValue = NULL;
    s_LabelCpuValue = NULL;
    s_LabelCpuTempValue = NULL;
    s_LabelMemValue = NULL;
    s_LabelDiskValue = NULL;
    s_NetDot = NULL;
    s_BarCpu = NULL;
    s_BarCpuTemp = NULL;
    s_BarMem = NULL;
    s_BarDisk = NULL;
    s_ButtonLeft = NULL;
    s_ButtonRight = NULL;
    s_ButtonEnter = NULL;
    s_ButtonExit = NULL;
}