// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTINGSCREENSECONDARY_H
#define UI_SETTINGSCREENSECONDARY_H

#include "ui_settings_types.h"

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingScreenSecondary
extern void ui_SettingScreenSecondary_screen_init(void);
extern void ui_SettingScreenSecondary_screen_destroy(void);
extern void ui_SettingScreenSecondary_set_snapshot(const ui_settings_snapshot_t *snapshot);
extern bool ui_settings_request_apply(const ui_settings_snapshot_t *snapshot);
extern bool ui_settings_request_save(const ui_settings_snapshot_t *snapshot);
extern lv_obj_t * ui_SettingScreenSecondary;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
