// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_StatusBar.h"

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define SETTINGS_VISIBLE_ROWS 4

typedef enum {
    SETTING_ITEM_WORK_MODE = 0,
    SETTING_ITEM_RGB_MODE,
    SETTING_ITEM_RGB_CLICK_MODE,
    SETTING_ITEM_RGB_COLOR,
    SETTING_ITEM_RGB_BRIGHTNESS,
    SETTING_ITEM_TFT_THEME,
    SETTING_ITEM_TFT_BRIGHTNESS,
    SETTING_ITEM_DEVICE_VOLUME,
    SETTING_ITEM_POWER_MODE,
    SETTING_ITEM_CONNECT_HOST,
    SETTING_ITEM_VOICE_ENABLE,
    SETTING_ITEM_PROFILE,
    SETTING_ITEM_COUNT
} setting_item_id_t;

typedef struct {
    const char *id;
    const char *hex;
    const char *name;
} setting_color_preset_t;

static const setting_color_preset_t k_setting_color_presets[] = {
    {"0", "ff0000", "红"},
    {"1", "ff4000", "橙红"},
    {"2", "ff8000", "橙"},
    {"3", "ffbf00", "金橙"},
    {"4", "ffff00", "黄"},
    {"5", "bfff00", "黄绿"},
    {"6", "80ff00", "青柠"},
    {"7", "40ff00", "亮绿"},
    {"8", "00ff00", "绿"},
    {"9", "00ff40", "春绿"},
    {"10", "00ff80", "薄荷"},
    {"11", "00ffbf", "青绿"},
    {"12", "00ffff", "青"},
    {"13", "00bfff", "天青"},
    {"14", "0080ff", "天蓝"},
    {"15", "0040ff", "亮蓝"},
    {"16", "0000ff", "蓝"},
    {"17", "4000ff", "靛蓝"},
    {"18", "8000ff", "紫"},
    {"19", "bf00ff", "兰紫"},
    {"20", "ff00ff", "品红"},
    {"21", "ff00bf", "玫红"},
    {"22", "ff0080", "粉红"},
    {"23", "ff0040", "绯红"}
};

lv_obj_t * ui_SettingScreenSecondary = NULL;
static lv_obj_t *ui_SettingSecondaryButtonLeft = NULL;
static lv_obj_t *ui_SettingSecondaryButtonRight = NULL;
static lv_obj_t *ui_SettingSecondaryButtonEnter = NULL;
static lv_obj_t *ui_SettingSecondaryButtonExit = NULL;
static lv_obj_t *ui_SettingSecondaryHeader = NULL;
static lv_obj_t *ui_SettingSecondaryTitle = NULL;
static lv_obj_t *ui_SettingSecondaryStatus = NULL;
static lv_obj_t *ui_SettingSecondaryPanel = NULL;
static lv_obj_t *ui_SettingSecondaryRows[SETTINGS_VISIBLE_ROWS] = {0};
static lv_obj_t *ui_SettingSecondaryNames[SETTINGS_VISIBLE_ROWS] = {0};
static lv_obj_t *ui_SettingSecondaryValues[SETTINGS_VISIBLE_ROWS] = {0};
static lv_obj_t *ui_SettingSecondaryFooter = NULL;
static lv_obj_t *ui_SettingSecondaryHintLeft = NULL;
static lv_obj_t *ui_SettingSecondaryHintCenter = NULL;
static lv_obj_t *ui_SettingSecondaryHintRight = NULL;
static lv_timer_t *s_setting_apply_timer = NULL;
static ui_settings_snapshot_t s_setting_edit = {
    .work_mode = 0,
    .rgb_mode = 0,
    .rgb_click_mode = 0,
    .rgb_brightness = 80,
    .tft_theme = 1,
    .tft_brightness = 80,
    .device_volume = 50,
    .power_mode = 0,
    .connect_host = true,
    .voice_enable = true,
    .active_keymap_profile = 0,
    .rgb_single_color = "0"
};
static bool s_setting_dirty = false;
static bool s_setting_waiting_apply = false;
static uint8_t s_setting_focus = 0;

static void setting_secondary_refresh(void);
static int setting_secondary_str_equal(const char *left, const char *right);

static bool setting_secondary_snapshot_equal(const ui_settings_snapshot_t *left,
                                             const ui_settings_snapshot_t *right)
{
    if (left == NULL || right == NULL) {
        return false;
    }

    return left->work_mode == right->work_mode &&
           left->rgb_mode == right->rgb_mode &&
           left->rgb_click_mode == right->rgb_click_mode &&
           left->rgb_brightness == right->rgb_brightness &&
           left->tft_theme == right->tft_theme &&
           left->tft_brightness == right->tft_brightness &&
           left->device_volume == right->device_volume &&
           left->power_mode == right->power_mode &&
           left->connect_host == right->connect_host &&
           left->voice_enable == right->voice_enable &&
           left->active_keymap_profile == right->active_keymap_profile &&
           setting_secondary_str_equal(left->rgb_single_color, right->rgb_single_color);
}

static int setting_secondary_str_equal(const char *left, const char *right)
{
    if (left == NULL || right == NULL) {
        return 0;
    }

    while (*left != '\0' && *right != '\0') {
        char left_char = *left;
        char right_char = *right;
        if (left_char >= 'A' && left_char <= 'F') {
            left_char = (char)(left_char - 'A' + 'a');
        }
        if (right_char >= 'A' && right_char <= 'F') {
            right_char = (char)(right_char - 'A' + 'a');
        }
        if (left_char != right_char) {
            return 0;
        }
        ++left;
        ++right;
    }

    return *left == *right;
}

static int setting_secondary_find_color_index(const char *hex)
{
    uint32_t index;
    for (index = 0; index < sizeof(k_setting_color_presets) / sizeof(k_setting_color_presets[0]); ++index) {
        if (setting_secondary_str_equal(k_setting_color_presets[index].id, hex) ||
            setting_secondary_str_equal(k_setting_color_presets[index].hex, hex)) {
            return (int)index;
        }
    }

    if (hex != NULL && *hex != '\0') {
        char *end_ptr = NULL;
        const long numeric_index = strtol(hex, &end_ptr, 10);
        const long max_index = (long)(sizeof(k_setting_color_presets) / sizeof(k_setting_color_presets[0])) - 1;
        if (end_ptr != hex && end_ptr != NULL && *end_ptr == '\0' && numeric_index >= 0 && numeric_index <= max_index) {
            return (int)numeric_index;
        }
    }

    return 0;
}

static void setting_secondary_copy_color(char *target, size_t target_size, const char *source)
{
    if (target == NULL || target_size == 0 || source == NULL) {
        return;
    }

    strncpy(target, source, target_size - 1);
    target[target_size - 1] = '\0';
}

static void setting_secondary_cancel_timer(void)
{
    if (s_setting_apply_timer != NULL) {
        lv_timer_del(s_setting_apply_timer);
        s_setting_apply_timer = NULL;
    }
}

static void setting_secondary_apply_timer_cb(lv_timer_t *timer)
{
    LV_UNUSED(timer);

    setting_secondary_cancel_timer();
    if (ui_settings_request_save(&s_setting_edit)) {
        s_setting_waiting_apply = false;
        s_setting_dirty = false;
    }
    setting_secondary_refresh();
}

static void setting_secondary_schedule_apply(void)
{
    setting_secondary_cancel_timer();
    s_setting_dirty = true;
    s_setting_waiting_apply = true;
    ui_settings_request_apply(&s_setting_edit);
    s_setting_apply_timer = lv_timer_create(setting_secondary_apply_timer_cb, 1000, NULL);
    setting_secondary_refresh();
}

static const char *setting_secondary_item_name(setting_item_id_t item)
{
    switch (item) {
        case SETTING_ITEM_WORK_MODE: return "工作模式";
        case SETTING_ITEM_RGB_MODE: return "背景灯效";
        case SETTING_ITEM_RGB_CLICK_MODE: return "点击灯效";
        case SETTING_ITEM_RGB_COLOR: return "单色灯光";
        case SETTING_ITEM_RGB_BRIGHTNESS: return "灯光亮度";
        case SETTING_ITEM_TFT_THEME: return "屏幕主题";
        case SETTING_ITEM_TFT_BRIGHTNESS: return "屏幕亮度";
        case SETTING_ITEM_DEVICE_VOLUME: return "设备音量";
        case SETTING_ITEM_POWER_MODE: return "电源模式";
        case SETTING_ITEM_CONNECT_HOST: return "连接上位机";
        case SETTING_ITEM_VOICE_ENABLE: return "语音输入";
        case SETTING_ITEM_PROFILE: return "键位配置";
        default: return "设置";
    }
}

static const char *setting_secondary_work_mode_text(int32_t value)
{
    switch (value) {
        case 0: return "有线";
        case 1: return "蓝牙";
        case 2: return "2.4G";
        default: return "有线";
    }
}

static const char *setting_secondary_rgb_mode_text(int32_t value)
{
    switch (value) {
        case 0: return "关闭";
        case 1: return "单色";
        case 2: return "彩虹";
        case 3: return "彩浪";
        case 4: return "循环";
        case 5: return "电平";
        case 6: return "火焰";
        case 7: return "脉冲";
        default: return "关闭";
    }
}

static const char *setting_secondary_rgb_click_mode_text(int32_t value)
{
    switch (value) {
        case 0: return "关闭";
        case 1: return "单色";
        case 2: return "渐变";
        default: return "关闭";
    }
}

static const char *setting_secondary_theme_text(int32_t value)
{
    switch (value) {
        case 1: return "主题 1";
        case 2: return "主题 2";
        case 3: return "主题 3";
        default: return "主题 1";
    }
}

static const char *setting_secondary_power_mode_text(int32_t value)
{
    switch (value) {
        case 0: return "正常";
        case 1: return "低功耗";
        case 2: return "浅休眠";
        case 3: return "深休眠";
        default: return "正常";
    }
}

static void setting_secondary_value_text(setting_item_id_t item, char *buffer, size_t buffer_size)
{
    if (buffer == NULL || buffer_size == 0) {
        return;
    }

    switch (item) {
        case SETTING_ITEM_WORK_MODE:
            snprintf(buffer, buffer_size, "%s", setting_secondary_work_mode_text(s_setting_edit.work_mode));
            break;
        case SETTING_ITEM_RGB_MODE:
            snprintf(buffer, buffer_size, "%s", setting_secondary_rgb_mode_text(s_setting_edit.rgb_mode));
            break;
        case SETTING_ITEM_RGB_CLICK_MODE:
            snprintf(buffer, buffer_size, "%s", setting_secondary_rgb_click_mode_text(s_setting_edit.rgb_click_mode));
            break;
        case SETTING_ITEM_RGB_COLOR: {
            const int color_index = setting_secondary_find_color_index(s_setting_edit.rgb_single_color);
            snprintf(buffer, buffer_size, "%s", k_setting_color_presets[color_index].name);
            break;
        }
        case SETTING_ITEM_RGB_BRIGHTNESS:
            snprintf(buffer, buffer_size, "%ld%%", (long)s_setting_edit.rgb_brightness);
            break;
        case SETTING_ITEM_TFT_THEME:
            snprintf(buffer, buffer_size, "%s", setting_secondary_theme_text(s_setting_edit.tft_theme));
            break;
        case SETTING_ITEM_TFT_BRIGHTNESS:
            snprintf(buffer, buffer_size, "%ld%%", (long)s_setting_edit.tft_brightness);
            break;
        case SETTING_ITEM_DEVICE_VOLUME:
            snprintf(buffer, buffer_size, "%ld%%", (long)s_setting_edit.device_volume);
            break;
        case SETTING_ITEM_POWER_MODE:
            snprintf(buffer, buffer_size, "%s", setting_secondary_power_mode_text(s_setting_edit.power_mode));
            break;
        case SETTING_ITEM_CONNECT_HOST:
            snprintf(buffer, buffer_size, "%s", s_setting_edit.connect_host ? "开启" : "关闭");
            break;
        case SETTING_ITEM_VOICE_ENABLE:
            snprintf(buffer, buffer_size, "%s", s_setting_edit.voice_enable ? "开启" : "关闭");
            break;
        case SETTING_ITEM_PROFILE:
            snprintf(buffer, buffer_size, "配置 %u", (unsigned)(s_setting_edit.active_keymap_profile + 1));
            break;
        default:
            snprintf(buffer, buffer_size, "--");
            break;
    }
}

static uint8_t setting_secondary_scroll_start(void)
{
    if (SETTING_ITEM_COUNT <= SETTINGS_VISIBLE_ROWS) {
        return 0;
    }
    if (s_setting_focus <= 1) {
        return 0;
    }
    if (s_setting_focus >= (SETTING_ITEM_COUNT - 2)) {
        return (uint8_t)(SETTING_ITEM_COUNT - SETTINGS_VISIBLE_ROWS);
    }
    return (uint8_t)(s_setting_focus - 1);
}

static void setting_secondary_update_status_text(void)
{
    if (ui_SettingSecondaryStatus == NULL) {
        return;
    }

    if (s_setting_waiting_apply) {
        lv_label_set_text(ui_SettingSecondaryStatus, "1秒后保存");
    } else if (s_setting_dirty) {
        lv_label_set_text(ui_SettingSecondaryStatus, "保存中");
    } else {
        lv_label_set_text(ui_SettingSecondaryStatus, "已同步");
    }
}

static void setting_secondary_refresh(void)
{
    uint8_t row_index;
    const uint8_t start = setting_secondary_scroll_start();

    setting_secondary_update_status_text();

    if (ui_SettingScreenSecondary == NULL) {
        return;
    }

    for (row_index = 0; row_index < SETTINGS_VISIBLE_ROWS; ++row_index) {
        const uint8_t item_index = (uint8_t)(start + row_index);
        char value_text[48] = {0};
        const bool active = item_index == s_setting_focus;

        if (item_index >= SETTING_ITEM_COUNT) {
            lv_obj_add_flag(ui_SettingSecondaryRows[row_index], LV_OBJ_FLAG_HIDDEN);
            continue;
        }

        lv_obj_clear_flag(ui_SettingSecondaryRows[row_index], LV_OBJ_FLAG_HIDDEN);
        lv_label_set_text(ui_SettingSecondaryNames[row_index], setting_secondary_item_name((setting_item_id_t)item_index));
        setting_secondary_value_text((setting_item_id_t)item_index, value_text, sizeof(value_text));
        lv_label_set_text(ui_SettingSecondaryValues[row_index], value_text);
                lv_obj_set_style_bg_color(ui_SettingSecondaryRows[row_index],
                                                                    active ? lv_color_hex(0x181E27) : lv_color_hex(0x121820),
                                                                    0);
                lv_obj_set_style_bg_opa(ui_SettingSecondaryRows[row_index], active ? LV_OPA_COVER : LV_OPA_90, 0);
                lv_obj_set_style_border_color(ui_SettingSecondaryRows[row_index],
                                                                            active ? lv_color_hex(0xD33A31) : lv_color_hex(0x2B3442),
                                                                            0);
        lv_obj_set_style_border_width(ui_SettingSecondaryRows[row_index], active ? 2 : 1, 0);
        lv_obj_set_style_text_color(ui_SettingSecondaryNames[row_index],
                                                                        active ? lv_color_hex(0xF5F7FA) : lv_color_hex(0xBAC5D3),
                                    0);
        lv_obj_set_style_text_color(ui_SettingSecondaryValues[row_index],
                                                                        active ? lv_color_hex(0xFFFFFF) : lv_color_hex(0x8FA0B5),
                                    0);
    }
}

static int setting_secondary_adjust_value(setting_item_id_t item, int step)
{
    const int color_count = (int)(sizeof(k_setting_color_presets) / sizeof(k_setting_color_presets[0]));

    switch (item) {
        case SETTING_ITEM_WORK_MODE: {
            const int32_t next = s_setting_edit.work_mode + step;
            if (next < 0 || next > 2 || next == s_setting_edit.work_mode) {
                return 0;
            }
            s_setting_edit.work_mode = next;
            return 1;
        }
        case SETTING_ITEM_RGB_MODE: {
            const int32_t next = s_setting_edit.rgb_mode + step;
            if (next < 0 || next > 7 || next == s_setting_edit.rgb_mode) {
                return 0;
            }
            s_setting_edit.rgb_mode = next;
            return 1;
        }
        case SETTING_ITEM_RGB_CLICK_MODE: {
            const int32_t next = s_setting_edit.rgb_click_mode + step;
            if (next < 0 || next > 2 || next == s_setting_edit.rgb_click_mode) {
                return 0;
            }
            s_setting_edit.rgb_click_mode = next;
            return 1;
        }
        case SETTING_ITEM_RGB_COLOR: {
            const int current = setting_secondary_find_color_index(s_setting_edit.rgb_single_color);
            int next = current + step;
            if (next < 0) {
                next = color_count - 1;
            } else if (next >= color_count) {
                next = 0;
            }
            if (next == current) {
                return 0;
            }
            setting_secondary_copy_color(s_setting_edit.rgb_single_color,
                                         sizeof(s_setting_edit.rgb_single_color),
                                         k_setting_color_presets[next].id);
            return 1;
        }
        case SETTING_ITEM_RGB_BRIGHTNESS: {
            const int32_t next = s_setting_edit.rgb_brightness + step * 5;
            const int32_t clamped = next < 0 ? 0 : (next > 100 ? 100 : next);
            if (clamped == s_setting_edit.rgb_brightness) {
                return 0;
            }
            s_setting_edit.rgb_brightness = clamped;
            return 1;
        }
        case SETTING_ITEM_TFT_THEME: {
            const int32_t next = s_setting_edit.tft_theme + step;
            if (next < 1 || next > 3 || next == s_setting_edit.tft_theme) {
                return 0;
            }
            s_setting_edit.tft_theme = next;
            return 1;
        }
        case SETTING_ITEM_TFT_BRIGHTNESS: {
            const int32_t next = s_setting_edit.tft_brightness + step * 5;
            const int32_t clamped = next < 5 ? 5 : (next > 100 ? 100 : next);
            if (clamped == s_setting_edit.tft_brightness) {
                return 0;
            }
            s_setting_edit.tft_brightness = clamped;
            return 1;
        }
        case SETTING_ITEM_DEVICE_VOLUME: {
            const int32_t next = s_setting_edit.device_volume + step * 5;
            const int32_t clamped = next < 0 ? 0 : (next > 100 ? 100 : next);
            if (clamped == s_setting_edit.device_volume) {
                return 0;
            }
            s_setting_edit.device_volume = clamped;
            return 1;
        }
        case SETTING_ITEM_POWER_MODE: {
            const int32_t next = s_setting_edit.power_mode + step;
            if (next < 0 || next > 3 || next == s_setting_edit.power_mode) {
                return 0;
            }
            s_setting_edit.power_mode = next;
            return 1;
        }
        case SETTING_ITEM_CONNECT_HOST:
            s_setting_edit.connect_host = !s_setting_edit.connect_host;
            return 1;
        case SETTING_ITEM_VOICE_ENABLE:
            s_setting_edit.voice_enable = !s_setting_edit.voice_enable;
            return 1;
        case SETTING_ITEM_PROFILE: {
            int next = (int)s_setting_edit.active_keymap_profile + step;
            if (next < 0) {
                next = UI_SETTINGS_PROFILE_COUNT - 1;
            } else if (next >= UI_SETTINGS_PROFILE_COUNT) {
                next = 0;
            }
            if (next == s_setting_edit.active_keymap_profile) {
                return 0;
            }
            s_setting_edit.active_keymap_profile = (uint8_t)next;
            return 1;
        }
        default:
            return 0;
    }
}

static void setting_secondary_forward_key(uint32_t key)
{
    lv_obj_t *active_screen = lv_scr_act();
    if (active_screen != NULL) {
        lv_event_send(active_screen, LV_EVENT_KEY, (void *)(uintptr_t)key);
    }
}

static void setting_secondary_screen_event_cb(lv_event_t *e)
{
    switch (lv_event_get_code(e)) {
        case LV_EVENT_SCREEN_LOADED:
            ui_StatusBar_show(false);
            setting_secondary_refresh();
            break;
        case LV_EVENT_SCREEN_UNLOADED:
            ui_StatusBar_show(true);
            break;
        default:
            break;
    }
}

static void setting_secondary_handle_key(int32_t key)
{
    if (key == LV_KEY_UP) {
        s_setting_focus = (uint8_t)((s_setting_focus == 0) ? (SETTING_ITEM_COUNT - 1) : (s_setting_focus - 1));
        setting_secondary_refresh();
        return;
    }

    if (key == LV_KEY_DOWN) {
        s_setting_focus = (uint8_t)((s_setting_focus + 1) % SETTING_ITEM_COUNT);
        setting_secondary_refresh();
        return;
    }

    if (key == LV_KEY_ENTER) {
        setting_secondary_refresh();
        return;
    }

    if (key == LV_KEY_ESC) {
        ui_set_active_screen_tag(UI_SCREEN_SETTING);
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingScreen_screen_init);
        lv_refr_now(NULL);
        return;
    }

    if ((key == LV_KEY_LEFT || key == LV_KEY_RIGHT) &&
        setting_secondary_adjust_value((setting_item_id_t)s_setting_focus, key == LV_KEY_RIGHT ? 1 : -1)) {
        setting_secondary_schedule_apply();
        return;
    }

    setting_secondary_refresh();
}

void ui_event_SettingScreenSecondary(lv_event_t * e)
{
    const lv_event_code_t event_code = lv_event_get_code(e);
    const uintptr_t key = (uintptr_t)lv_event_get_param(e);

    if (event_code == LV_EVENT_KEY) {
        setting_secondary_handle_key((int32_t)key);
    }
}

void ui_event_ButtonLeft6(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        setting_secondary_forward_key(LV_KEY_LEFT);
    }
}

void ui_event_ButtonRight6(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        setting_secondary_forward_key(LV_KEY_RIGHT);
    }
}

void ui_event_ButtonEnter6(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        setting_secondary_forward_key(LV_KEY_ENTER);
    }
}

void ui_event_ButtonExit6(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        setting_secondary_forward_key(LV_KEY_ESC);
    }
}

void ui_SettingScreenSecondary_set_snapshot(const ui_settings_snapshot_t *snapshot)
{
    if (snapshot == NULL) {
        return;
    }

    if ((s_setting_dirty || s_setting_waiting_apply) && setting_secondary_snapshot_equal(snapshot, &s_setting_edit)) {
        setting_secondary_refresh();
        return;
    }

    s_setting_edit = *snapshot;
    s_setting_dirty = false;
    s_setting_waiting_apply = false;
    setting_secondary_cancel_timer();
    setting_secondary_refresh();
}

void ui_SettingScreenSecondary_screen_init(void)
{
    uint8_t row_index;

    ui_set_active_screen_tag(UI_SCREEN_SETTING_SECONDARY);
    ui_SettingScreenSecondary = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingScreenSecondary, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_SettingScreenSecondary, lv_color_hex(0x070A0F), 0);
    lv_obj_set_style_bg_opa(ui_SettingScreenSecondary, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(ui_SettingScreenSecondary, 0, 0);
    lv_obj_set_style_radius(ui_SettingScreenSecondary, 0, 0);
    lv_obj_set_style_pad_all(ui_SettingScreenSecondary, 0, 0);

    ui_SettingSecondaryButtonLeft = lv_btn_create(ui_SettingScreenSecondary);
    lv_obj_set_size(ui_SettingSecondaryButtonLeft, 52, 40);
    lv_obj_align(ui_SettingSecondaryButtonLeft, LV_ALIGN_LEFT_MID, 0, 0);
    lv_obj_set_style_bg_opa(ui_SettingSecondaryButtonLeft, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_SettingSecondaryButtonLeft, 0, 0);

    ui_SettingSecondaryButtonRight = lv_btn_create(ui_SettingScreenSecondary);
    lv_obj_set_size(ui_SettingSecondaryButtonRight, 52, 40);
    lv_obj_align(ui_SettingSecondaryButtonRight, LV_ALIGN_RIGHT_MID, 0, 0);
    lv_obj_set_style_bg_opa(ui_SettingSecondaryButtonRight, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_SettingSecondaryButtonRight, 0, 0);

    ui_SettingSecondaryButtonEnter = lv_btn_create(ui_SettingScreenSecondary);
    lv_obj_set_size(ui_SettingSecondaryButtonEnter, 120, 34);
    lv_obj_align(ui_SettingSecondaryButtonEnter, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_set_style_bg_opa(ui_SettingSecondaryButtonEnter, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_SettingSecondaryButtonEnter, 0, 0);

    ui_SettingSecondaryButtonExit = lv_btn_create(ui_SettingScreenSecondary);
    lv_obj_set_size(ui_SettingSecondaryButtonExit, 72, 28);
    lv_obj_align(ui_SettingSecondaryButtonExit, LV_ALIGN_TOP_LEFT, 0, 0);
    lv_obj_set_style_bg_opa(ui_SettingSecondaryButtonExit, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_SettingSecondaryButtonExit, 0, 0);

    ui_SettingSecondaryHeader = lv_obj_create(ui_SettingScreenSecondary);
    lv_obj_set_size(ui_SettingSecondaryHeader, 420, 30);
    lv_obj_align(ui_SettingSecondaryHeader, LV_ALIGN_TOP_MID, 0, 4);
    lv_obj_clear_flag(ui_SettingSecondaryHeader, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_SettingSecondaryHeader, 10, 0);
    lv_obj_set_style_bg_color(ui_SettingSecondaryHeader, lv_color_hex(0x0C0F14), 0);
    lv_obj_set_style_bg_opa(ui_SettingSecondaryHeader, LV_OPA_COVER, 0);
    lv_obj_set_style_border_color(ui_SettingSecondaryHeader, lv_color_hex(0x273242), 0);
    lv_obj_set_style_border_width(ui_SettingSecondaryHeader, 1, 0);
    lv_obj_set_style_pad_all(ui_SettingSecondaryHeader, 0, 0);

    ui_SettingSecondaryTitle = lv_label_create(ui_SettingSecondaryHeader);
    lv_obj_align(ui_SettingSecondaryTitle, LV_ALIGN_LEFT_MID, 14, 0);
    lv_label_set_text(ui_SettingSecondaryTitle, "系统设置");
    lv_obj_set_style_text_font(ui_SettingSecondaryTitle, &ui_font_FontCKJGT16, 0);
    lv_obj_set_style_text_color(ui_SettingSecondaryTitle, lv_color_hex(0xF5F7FA), 0);

    ui_SettingSecondaryStatus = lv_label_create(ui_SettingSecondaryHeader);
    lv_obj_align(ui_SettingSecondaryStatus, LV_ALIGN_RIGHT_MID, -14, 0);
    lv_label_set_text(ui_SettingSecondaryStatus, "已同步");
    lv_obj_set_style_text_font(ui_SettingSecondaryStatus, &ui_font_FontCKJGT16, 0);
    lv_obj_set_style_text_color(ui_SettingSecondaryStatus, lv_color_hex(0xD33A31), 0);

    ui_SettingSecondaryPanel = lv_obj_create(ui_SettingScreenSecondary);
    lv_obj_set_size(ui_SettingSecondaryPanel, 420, 104);
    lv_obj_align(ui_SettingSecondaryPanel, LV_ALIGN_TOP_MID, 0, 36);
    lv_obj_clear_flag(ui_SettingSecondaryPanel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_SettingSecondaryPanel, 12, 0);
    lv_obj_set_style_bg_color(ui_SettingSecondaryPanel, lv_color_hex(0x121820), 0);
    lv_obj_set_style_bg_opa(ui_SettingSecondaryPanel, LV_OPA_COVER, 0);
    lv_obj_set_style_border_color(ui_SettingSecondaryPanel, lv_color_hex(0x273242), 0);
    lv_obj_set_style_border_width(ui_SettingSecondaryPanel, 1, 0);
    lv_obj_set_style_pad_all(ui_SettingSecondaryPanel, 4, 0);

    for (row_index = 0; row_index < SETTINGS_VISIBLE_ROWS; ++row_index) {
        ui_SettingSecondaryRows[row_index] = lv_obj_create(ui_SettingSecondaryPanel);
        lv_obj_set_size(ui_SettingSecondaryRows[row_index], 404, 22);
        lv_obj_align(ui_SettingSecondaryRows[row_index], LV_ALIGN_TOP_MID, 0, 1 + (int32_t)row_index * 24);
        lv_obj_clear_flag(ui_SettingSecondaryRows[row_index], LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_radius(ui_SettingSecondaryRows[row_index], 7, 0);
        lv_obj_set_style_pad_left(ui_SettingSecondaryRows[row_index], 12, 0);
        lv_obj_set_style_pad_right(ui_SettingSecondaryRows[row_index], 12, 0);
        lv_obj_set_style_pad_top(ui_SettingSecondaryRows[row_index], 1, 0);
        lv_obj_set_style_pad_bottom(ui_SettingSecondaryRows[row_index], 1, 0);
        lv_obj_set_style_shadow_width(ui_SettingSecondaryRows[row_index], 0, 0);

        ui_SettingSecondaryNames[row_index] = lv_label_create(ui_SettingSecondaryRows[row_index]);
        lv_obj_align(ui_SettingSecondaryNames[row_index], LV_ALIGN_LEFT_MID, 0, 0);
        lv_obj_set_style_text_font(ui_SettingSecondaryNames[row_index], &ui_font_FontCKJGT16, 0);
        lv_obj_set_style_text_color(ui_SettingSecondaryNames[row_index], lv_color_hex(0xB6C8D9), 0);

        ui_SettingSecondaryValues[row_index] = lv_label_create(ui_SettingSecondaryRows[row_index]);
        lv_obj_align(ui_SettingSecondaryValues[row_index], LV_ALIGN_RIGHT_MID, 0, 0);
        lv_obj_set_style_text_font(ui_SettingSecondaryValues[row_index], &ui_font_FontCKJGT16, 0);
        lv_obj_set_style_text_color(ui_SettingSecondaryValues[row_index], lv_color_hex(0xEAF4FF), 0);
    }

    lv_obj_add_event_cb(ui_SettingSecondaryButtonLeft, ui_event_ButtonLeft6, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SettingSecondaryButtonRight, ui_event_ButtonRight6, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SettingSecondaryButtonEnter, ui_event_ButtonEnter6, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SettingSecondaryButtonExit, ui_event_ButtonExit6, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SettingScreenSecondary, ui_event_SettingScreenSecondary, LV_EVENT_KEY, NULL);
    lv_obj_add_event_cb(ui_SettingScreenSecondary, setting_secondary_screen_event_cb, LV_EVENT_ALL, NULL);

    setting_secondary_refresh();
}

void ui_SettingScreenSecondary_screen_destroy(void)
{
    setting_secondary_cancel_timer();

    if (ui_SettingScreenSecondary != NULL) {
        lv_obj_del(ui_SettingScreenSecondary);
    }

    ui_SettingScreenSecondary = NULL;
    ui_SettingSecondaryButtonLeft = NULL;
    ui_SettingSecondaryButtonRight = NULL;
    ui_SettingSecondaryButtonEnter = NULL;
    ui_SettingSecondaryButtonExit = NULL;
    ui_SettingSecondaryHeader = NULL;
    ui_SettingSecondaryTitle = NULL;
    ui_SettingSecondaryStatus = NULL;
    ui_SettingSecondaryPanel = NULL;
    ui_SettingSecondaryFooter = NULL;
    ui_SettingSecondaryHintLeft = NULL;
    ui_SettingSecondaryHintCenter = NULL;
    ui_SettingSecondaryHintRight = NULL;

    memset(ui_SettingSecondaryRows, 0, sizeof(ui_SettingSecondaryRows));
    memset(ui_SettingSecondaryNames, 0, sizeof(ui_SettingSecondaryNames));
    memset(ui_SettingSecondaryValues, 0, sizeof(ui_SettingSecondaryValues));
}