; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3minin4r2]
board = esp32-s3-devkitc-1
platform = espressif32@6.3.2
framework = arduino
board_build.arduino.memory_type = qio_qspi
board_upload.flash_size = 4MB
board_build.partitions = partitions-4MB.csv
board_build.filesystem = spiffs
monitor_speed = 115200
board_build.usb_mode = tinyusb
board_build.usb_cdc = 1
board_build.usb_hid = consumer_keyboard
lib_deps = 
	t-vk/ESP32 BLE Keyboard@^0.3.2
	fastled/FastLED@^3.10.1
	esphome/ESP32-audioI2S@^2.3.0
	https://github.com/brofield/simpleini/archive/refs/tags/v4.19.zip
	bodmer/TFT_eSPI@^2.5.43
	lvgl/lvgl@8.3.11
	madhephaestus/ESP32Encoder@^0.10.2
	mathertel/OneButton@^2.6.1
	arduino-libraries/NTPClient@^3.2.1
	bblanchon/ArduinoJson@6.19.4
	kosme/arduinoFFT@^2.0.4
build_src_filter = 
	+<*>
	-<ui/ui_font_BebasNeueFont32.c>
	-<ui/ui_font_BebasNeueFont64.c>
	-<ui/ui_font_BebasNeueFont80.c>
	-<ui/ui_font_FontCKJGT32.c>
	-<ui/ui_font_FontCKJGT40.c>
	-<ui/ui_font_FontCKJGT48.c>
	-<ui/ui_font_FontCKJGT64.c>
	-<ui/ui_font_FontCKJGT80.c>
build_flags = 
	-Iinclude
	-DBOARD_HAS_PSRAM
	-DLV_CONF_PATH=lv_conf_local.h
	-mfix-esp32-psram-cache-issue
	-DCONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=1
	-DCONFIG_BT_BLE_DYNAMIC_ENV_MEMORY=1
	-DCONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM=4
	-DCONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM=8
	-DCONFIG_ESP_WIFI_TX_BUFFER_TYPE=1
	-DCONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM=8
	-DCONFIG_BTDM_CTRL_BLE_MAX_CONN=1
	-DCONFIG_BTDM_CTRL_BR_EDR_SYNC_CONN_ENABLED=0
	-DCONFIG_BT_BLE_FEAT_SUPPORT_COMBINE=0
	-DCONFIG_BT_BLUEDROID_MEM_DEBUG=0
	-DARDUINO_USB_MODE=1
	-DCONFIG_TINYUSB_HID_ENABLED=1
	-DCONFIG_TINYUSB_CDC_ENABLED=1
	-DCONFIG_TINYUSB_HID_CONSUMER_CONTROL=1
	-DENABLE_VOICE_ASR_MAINTASK=1
	-DENABLE_EXTENSION_MODULES=0
	-DCONFIG_COMPILER_STACK_CHECK_MODE_ALL=y
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
build_unflags = 
board_build.f_flash = 80000000L
board_build.flash_mode = qio
